### ISSUE TITLE
Custom style for bars

### ISSUE THREAD

**Issue by sepehr1313** [lannex/react-password-strength-bar#26]
While using the library I figured out It's not possible to style the bars and the only prop it has is to change the colors.
https://github.com/lannex/react-password-strength-bar/blob/master/lib/Item.tsx#L9
It would be nice to add that feature. I can raise a PR for that if it's possible.

**Comment by lannex** [comment]
Thank you. I'll consider it!

**Comment by mrkvon** [comment]
For the moment, i use the following to style the bars:

component:
```jsx
<PasswordStrengthBar
  password={password}
  className="passwordStrengthBar"
/>
```

stylesheet:
```scss
.passwordStrengthBar > div > div {
  height: 5px !important;
  // add whatever style you need
  // but the word "!important" is important
  // you may also use :nth-child pseudoselector to target specific bars
  // https://css-tricks.com/almanac/selectors/n/nth-child/
}
```

Hope this helps
